// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuC6h4pfy1jAhn04qfylXq6z7pnhJbuY',
    appId: '1:550409635864:web:c95bd5d849934f63c15b6d',
    messagingSenderId: '550409635864',
    projectId: 'tomatoes-6bc10',
    authDomain: 'tomatoes-6bc10.firebaseapp.com',
    storageBucket: 'tomatoes-6bc10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKelROnggHJ1t85x476T3iJ6sRu2O8u9Q',
    appId: '1:550409635864:android:8e97c7170e76e2b1c15b6d',
    messagingSenderId: '550409635864',
    projectId: 'tomatoes-6bc10',
    storageBucket: 'tomatoes-6bc10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdyAkiyPlg93HGRmf_1p6sNx3ig39b40c',
    appId: '1:550409635864:ios:483d5afb677bd4d5c15b6d',
    messagingSenderId: '550409635864',
    projectId: 'tomatoes-6bc10',
    storageBucket: 'tomatoes-6bc10.appspot.com',
    iosClientId: '550409635864-nhi7s4pubed45u9uenk1s4vcqho3u8l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomatoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdyAkiyPlg93HGRmf_1p6sNx3ig39b40c',
    appId: '1:550409635864:ios:ed43bf001c576190c15b6d',
    messagingSenderId: '550409635864',
    projectId: 'tomatoes-6bc10',
    storageBucket: 'tomatoes-6bc10.appspot.com',
    iosClientId: '550409635864-elapk41qderg90t34o1b9u87798r19is.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomatoes.RunnerTests',
  );
}
